
FROM python:3.11-bullseye


WORKDIR /app


COPY ./ /app

RUN python -m pip install --upgrade pip


RUN python -m pip install --no-cache-dir -r requirements.txt


EXPOSE 8000


CMD ["gunicorn", "-b", "0.0.0.0:8000", "main:app"]

